### ISSUE TITLE
How to implement backend

### ISSUE THREAD

**Issue by all-mute** [engageintellect/project-nexum#5]
Hi! I really like your project and want to implement similar website for interview questions with a friend. I'm happy that I found you! Can you please share your backend scheme? <3

I'm familiar with pocketbase. I would really appreciate if you will send to me https://t.me/nonGilgamesh your backend's migration or archived pocketbase directory. (in case you have notNan-politics on in some columns)

Thanks)

**Comment by all-mute** [comment]
@engageintellect sorry i forgot to assign you

**Comment by engageintellect** [comment]
Hey @all-mute,

Stoked to hear that you like this project. I have included the current schema for you to import into your pocketbase instance.

Let me know if you need anything else from me, happy to help however I can. 👍
[pb_schema.json](https://github.com/engageintellect/project-nexum/files/15183201/pb_schema.json)

**Comment by all-mute** [comment]
Ow I'm so glad you answered! Thank you for the schema )
